package com.singlepointsol.imagesassignmentlazygrid

data class Image(val image: Int, val name: String)
fun getAllImages(): ArrayList<Image> {
return arrayListOf(
Image(R.drawable.i10, "Hyundai i10"),
Image(R.drawable.i30, "Hyundai i30"),
Image(R.drawable.pie, "Android Pie"),
Image(R.drawable.kona, "Android Kona"),
Image(R.drawable.oreo, "Android Oreo"),
Image(R.drawable.bugatticentodieci, "Bugatti Centi Dieci"),
Image(R.drawable.bugattidivo, "Bugatti Divo"),
Image(R.drawable.bugattilavoiturenoire, "Bugatti Lavoiturenoire"),
Image(R.drawable.creta, "Hyundai Creta"),
Image(R.drawable.oreo, "Android Oero"),
Image(R.drawable.cupcake, "Android CupCake"),
Image(R.drawable.donut, "Android Donut"),
Image(R.drawable.kitkat, "Android KitKat"),
Image(R.drawable.marshamallow, "Android Marsh Mallow"),
Image(R.drawable.mercedesbenzexelero, "Mercedes Benz Exelero"),
Image(R.drawable.nougat, "Android Nougat"),
Image(R.drawable.rollsroyceboattailphotoroom, "Rolls Royce Boat Tail "),
Image(R.drawable.rollsroycelarosenoiredroptailphotoroom, "Rolls Royce Arosenoi Redroptail"),
Image(R.drawable.paganizondahpbarchetta, "Paganizondahpbarchetta"),
Image(R.drawable.paganihuatya, "Pagani Huatya"),
Image(R.drawable.rollsroycesweptail, "Rolls Royce Sweptail"),
Image(R.drawable.santro, "Hyundai Santro"),
Image(R.drawable.spautomotivechaos, "Sp Automotive Chaos"),
Image(R.drawable.venue, "Hyundai Venue"),
Image(R.drawable.creta, "Hyundai Creata"),
Image(R.drawable.santro, "Hyundai Santro"),
Image(R.drawable.i30, "Hyundai Santro"),
    Image(R.drawable.i10, "Hyundai i10"),
    Image(R.drawable.i30, "Hyundai i30"),
    Image(R.drawable.pie, "Android Pie"),
    Image(R.drawable.kona, "Android Kona"),
    Image(R.drawable.oreo, "Android Oreo"),
    Image(R.drawable.bugatticentodieci, "Bugatti Centi Dieci"),
    Image(R.drawable.bugattidivo, "Bugatti Divo"),
    Image(R.drawable.bugattilavoiturenoire, "Bugatti Lavoiturenoire"),
    Image(R.drawable.creta, "Hyundai Creta"),
    Image(R.drawable.oreo, "Android Oero"),
    Image(R.drawable.cupcake, "Android CupCake"),
    Image(R.drawable.donut, "Android Donut"),
    Image(R.drawable.kitkat, "Android KitKat"),
    Image(R.drawable.marshamallow, "Android Marsh Mallow"),
    Image(R.drawable.mercedesbenzexelero, "Mercedes Benz Exelero"),
    Image(R.drawable.nougat, "Android Nougat"),
    Image(R.drawable.rollsroyceboattailphotoroom, "Rolls Royce Boat Tail "),
    Image(R.drawable.rollsroycelarosenoiredroptailphotoroom, "Rolls Royce Arosenoi Redroptail"),
    Image(R.drawable.paganizondahpbarchetta, "Paganizondahpbarchetta"),
    Image(R.drawable.paganihuatya, "Pagani Huatya"),
    Image(R.drawable.rollsroycesweptail, "Rolls Royce Sweptail"),
    Image(R.drawable.santro, "Hyundai Santro"),
    Image(R.drawable.spautomotivechaos, "Sp Automotive Chaos"),
    Image(R.drawable.venue, "Hyundai Venue"),
    Image(R.drawable.creta, "Hyundai Creata"),
    Image(R.drawable.santro, "Hyundai Santro"),
    Image(R.drawable.i30, "Hyundai Santro"),
    Image(R.drawable.i10, "Hyundai i10"),
    Image(R.drawable.i30, "Hyundai i30"),
    Image(R.drawable.pie, "Android Pie"),
    Image(R.drawable.kona, "Android Kona"),
    Image(R.drawable.oreo, "Android Oreo"),
    Image(R.drawable.bugatticentodieci, "Bugatti Centi Dieci"),
    Image(R.drawable.bugattidivo, "Bugatti Divo"),
    Image(R.drawable.bugattilavoiturenoire, "Bugatti Lavoiturenoire"),
    Image(R.drawable.creta, "Hyundai Creta"),
    Image(R.drawable.oreo, "Android Oero"),
    Image(R.drawable.cupcake, "Android CupCake"),
    Image(R.drawable.donut, "Android Donut"),
    Image(R.drawable.kitkat, "Android KitKat"),
    Image(R.drawable.marshamallow, "Android Marsh Mallow"),
    Image(R.drawable.mercedesbenzexelero, "Mercedes Benz Exelero"),
    Image(R.drawable.nougat, "Android Nougat"),
    Image(R.drawable.rollsroyceboattailphotoroom, "Rolls Royce Boat Tail "),
    Image(R.drawable.rollsroycelarosenoiredroptailphotoroom, "Rolls Royce Arosenoi Redroptail"),
    Image(R.drawable.paganizondahpbarchetta, "Paganizondahpbarchetta"),
    Image(R.drawable.paganihuatya, "Pagani Huatya"),
    Image(R.drawable.rollsroycesweptail, "Rolls Royce Sweptail"),
    Image(R.drawable.santro, "Hyundai Santro"),
    Image(R.drawable.spautomotivechaos, "Sp Automotive Chaos"),
    Image(R.drawable.venue, "Hyundai Venue"),
    Image(R.drawable.creta, "Hyundai Creata"),
    Image(R.drawable.santro, "Hyundai Santro"),
    Image(R.drawable.i30, "Hyundai Santro"),
    Image(R.drawable.i10, "Hyundai i10"),
    Image(R.drawable.i30, "Hyundai i30"),
    Image(R.drawable.pie, "Android Pie"),
    Image(R.drawable.kona, "Android Kona"),
    Image(R.drawable.oreo, "Android Oreo"),
    Image(R.drawable.bugatticentodieci, "Bugatti Centi Dieci"),
    Image(R.drawable.bugattidivo, "Bugatti Divo"),
    Image(R.drawable.bugattilavoiturenoire, "Bugatti Lavoiturenoire"),
    Image(R.drawable.creta, "Hyundai Creta"),
    Image(R.drawable.oreo, "Android Oero"),
    Image(R.drawable.cupcake, "Android CupCake"),
    Image(R.drawable.donut, "Android Donut"),
    Image(R.drawable.kitkat, "Android KitKat"),
    Image(R.drawable.marshamallow, "Android Marsh Mallow"),
    Image(R.drawable.mercedesbenzexelero, "Mercedes Benz Exelero"),
    Image(R.drawable.nougat, "Android Nougat"),
    Image(R.drawable.rollsroyceboattailphotoroom, "Rolls Royce Boat Tail "),
    Image(R.drawable.rollsroycelarosenoiredroptailphotoroom, "Rolls Royce Arosenoi Redroptail"),
    Image(R.drawable.paganizondahpbarchetta, "Paganizondahpbarchetta"),
    Image(R.drawable.paganihuatya, "Pagani Huatya"),
    Image(R.drawable.rollsroycesweptail, "Rolls Royce Sweptail"),
    Image(R.drawable.santro, "Hyundai Santro"),
    Image(R.drawable.spautomotivechaos, "Sp Automotive Chaos"),
    Image(R.drawable.venue, "Hyundai Venue"),
    Image(R.drawable.creta, "Hyundai Creata"),
    Image(R.drawable.santro, "Hyundai Santro"),
    Image(R.drawable.i30, "Hyundai Santro"),
    Image(R.drawable.i10, "Hyundai i10"),
    Image(R.drawable.i30, "Hyundai i30"),
    Image(R.drawable.pie, "Android Pie"),
    Image(R.drawable.kona, "Android Kona"),
    Image(R.drawable.oreo, "Android Oreo"),
    Image(R.drawable.bugatticentodieci, "Bugatti Centi Dieci"),
    Image(R.drawable.bugattidivo, "Bugatti Divo"),
    Image(R.drawable.bugattilavoiturenoire, "Bugatti Lavoiturenoire"),
    Image(R.drawable.creta, "Hyundai Creta"),
    Image(R.drawable.oreo, "Android Oero"),
    Image(R.drawable.cupcake, "Android CupCake"),
    Image(R.drawable.donut, "Android Donut"),
    Image(R.drawable.kitkat, "Android KitKat"),
    Image(R.drawable.marshamallow, "Android Marsh Mallow"),
    Image(R.drawable.mercedesbenzexelero, "Mercedes Benz Exelero"),
    Image(R.drawable.nougat, "Android Nougat"),
    Image(R.drawable.rollsroyceboattailphotoroom, "Rolls Royce Boat Tail "),
    Image(R.drawable.rollsroycelarosenoiredroptailphotoroom, "Rolls Royce Arosenoi Redroptail"),
    Image(R.drawable.paganizondahpbarchetta, "Paganizondahpbarchetta"),
    Image(R.drawable.paganihuatya, "Pagani Huatya"),
    Image(R.drawable.rollsroycesweptail, "Rolls Royce Sweptail"),
    Image(R.drawable.santro, "Hyundai Santro"),
    Image(R.drawable.spautomotivechaos, "Sp Automotive Chaos"),
    Image(R.drawable.venue, "Hyundai Venue"),
    Image(R.drawable.creta, "Hyundai Creata"),
    Image(R.drawable.santro, "Hyundai Santro"),
    Image(R.drawable.i30, "Hyundai Santro"),
    Image(R.drawable.i10, "Hyundai i10"),
    Image(R.drawable.i30, "Hyundai i30"),
    Image(R.drawable.pie, "Android Pie"),
    Image(R.drawable.kona, "Android Kona"),
    Image(R.drawable.oreo, "Android Oreo"),
    Image(R.drawable.bugatticentodieci, "Bugatti Centi Dieci"),
    Image(R.drawable.bugattidivo, "Bugatti Divo"),
    Image(R.drawable.bugattilavoiturenoire, "Bugatti Lavoiturenoire"),
    Image(R.drawable.creta, "Hyundai Creta"),
    Image(R.drawable.oreo, "Android Oero"),
    Image(R.drawable.cupcake, "Android CupCake"),
    Image(R.drawable.donut, "Android Donut"),
    Image(R.drawable.kitkat, "Android KitKat"),
    Image(R.drawable.marshamallow, "Android Marsh Mallow"),
    Image(R.drawable.mercedesbenzexelero, "Mercedes Benz Exelero"),
    Image(R.drawable.nougat, "Android Nougat"),
    Image(R.drawable.rollsroyceboattailphotoroom, "Rolls Royce Boat Tail "),
    Image(R.drawable.rollsroycelarosenoiredroptailphotoroom, "Rolls Royce Arosenoi Redroptail"),
    Image(R.drawable.paganizondahpbarchetta, "Paganizondahpbarchetta"),
    Image(R.drawable.paganihuatya, "Pagani Huatya"),
    Image(R.drawable.rollsroycesweptail, "Rolls Royce Sweptail"),
    Image(R.drawable.santro, "Hyundai Santro"),
    Image(R.drawable.spautomotivechaos, "Sp Automotive Chaos"),
    Image(R.drawable.venue, "Hyundai Venue"),
    Image(R.drawable.creta, "Hyundai Creata"),
    Image(R.drawable.santro, "Hyundai Santro"),
    Image(R.drawable.i30, "Hyundai Santro"))
}